var dir_e91d843e8f0aa7d6b92ea0c09cf9089b =
[
    [ "cedit.c", "cedit_8c.html", "cedit_8c" ],
    [ "cedit.h", "cedit_8h.html", "cedit_8h" ],
    [ "curve.c", "curve_8c.html", "curve_8c" ],
    [ "curve.h", "curve_8h.html", "curve_8h" ],
    [ "cwidget.c", "cwidget_8c.html", "cwidget_8c" ],
    [ "datab.c", "datab_8c.html", "datab_8c" ],
    [ "datab.h", "datab_8h.html", "datab_8h" ],
    [ "draw.c", "draw_8c.html", "draw_8c" ],
    [ "frame.c", "frame_8c.html", "frame_8c" ],
    [ "glyph.c", "glyph_8c.html", "glyph_8c" ],
    [ "labels.c", "labels_8c.html", "labels_8c" ],
    [ "legend.c", "legend_8c.html", "legend_8c" ],
    [ "m_curve.c", "m__curve_8c.html", "m__curve_8c" ],
    [ "show.c", "show_8c.html", "show_8c" ],
    [ "tab-1.c", "tab-1_8c.html", "tab-1_8c" ],
    [ "tab-2.c", "tab-2_8c.html", "tab-2_8c" ],
    [ "tab-3.c", "tab-3_8c.html", "tab-3_8c" ],
    [ "tab-4.c", "tab-4_8c.html", "tab-4_8c" ],
    [ "title.c", "title_8c.html", "title_8c" ],
    [ "w_curve.c", "w__curve_8c.html", "w__curve_8c" ],
    [ "w_data.c", "w__data_8c.html", "w__data_8c" ],
    [ "w_img.c", "w__img_8c.html", "w__img_8c" ],
    [ "xaxis.c", "xaxis_8c.html", "xaxis_8c" ],
    [ "yaxis.c", "yaxis_8c.html", "yaxis_8c" ]
];