var searchData=
[
  ['cell_5fedition_0',['cell_edition',['../structcell__edition.html',1,'']]],
  ['cell_5ffile_1',['cell_file',['../structcell__file.html',1,'']]],
  ['cell_5finfo_2',['cell_info',['../structcell__info.html',1,'']]],
  ['cextra_3',['cextra',['../structcextra.html',1,'']]],
  ['chemical_5fdata_4',['chemical_data',['../structchemical__data.html',1,'']]],
  ['cif_5fdata_5',['cif_data',['../structcif__data.html',1,'']]],
  ['cif_5ffile_6',['cif_file',['../structcif__file.html',1,'']]],
  ['classical_5ffield_7',['classical_field',['../structclassical__field.html',1,'']]],
  ['color_8',['color',['../structcolor.html',1,'']]],
  ['colormap_9',['colormap',['../structcolormap.html',1,'']]],
  ['colrgba_10',['ColRGBA',['../struct_col_r_g_b_a.html',1,'']]],
  ['coord_5fedition_11',['coord_edition',['../structcoord__edition.html',1,'']]],
  ['coord_5ffile_12',['coord_file',['../structcoord__file.html',1,'']]],
  ['coord_5finfo_13',['coord_info',['../structcoord__info.html',1,'']]],
  ['cp2k_14',['cp2k',['../structcp2k.html',1,'']]],
  ['cpmd_15',['cpmd',['../structcpmd.html',1,'']]],
  ['crystal_5fdata_16',['crystal_data',['../structcrystal__data.html',1,'']]],
  ['curve_17',['curve',['../structcurve.html',1,'']]],
  ['curvestate_18',['CurveState',['../struct_curve_state.html',1,'']]]
];
