var searchData=
[
  ['cell_5fedition_0',['cell_edition',['../d4/d03/structcell__edition.html',1,'']]],
  ['cell_5ffile_1',['cell_file',['../d4/d9d/structcell__file.html',1,'']]],
  ['cell_5finfo_2',['cell_info',['../de/df1/structcell__info.html',1,'']]],
  ['cextra_3',['cextra',['../d5/de2/structcextra.html',1,'']]],
  ['chemical_5fdata_4',['chemical_data',['../da/d11/structchemical__data.html',1,'']]],
  ['cif_5fdata_5',['cif_data',['../d2/d95/structcif__data.html',1,'']]],
  ['cif_5ffile_6',['cif_file',['../dd/d8e/structcif__file.html',1,'']]],
  ['classical_5ffield_7',['classical_field',['../d6/da3/structclassical__field.html',1,'']]],
  ['color_8',['color',['../d0/d91/structcolor.html',1,'']]],
  ['colormap_9',['colormap',['../d9/d58/structcolormap.html',1,'']]],
  ['colrgba_10',['ColRGBA',['../d1/d74/struct_col_r_g_b_a.html',1,'']]],
  ['coord_5fedition_11',['coord_edition',['../de/d4a/structcoord__edition.html',1,'']]],
  ['coord_5ffile_12',['coord_file',['../d0/d2f/structcoord__file.html',1,'']]],
  ['coord_5finfo_13',['coord_info',['../df/ddc/structcoord__info.html',1,'']]],
  ['cp2k_14',['cp2k',['../dd/d27/structcp2k.html',1,'']]],
  ['cpmd_15',['cpmd',['../da/d1f/structcpmd.html',1,'']]],
  ['crystal_5fdata_16',['crystal_data',['../d8/d1b/structcrystal__data.html',1,'']]],
  ['curve_17',['curve',['../d7/d01/structcurve.html',1,'']]],
  ['curvestate_18',['CurveState',['../dd/d12/struct_curve_state.html',1,'']]]
];
