var searchData=
[
  ['cell_5fedition_0',['cell_edition',['../d4/d03/structcell__edition.html',1,'']]],
  ['cell_5ffile_1',['cell_file',['../d4/d9d/structcell__file.html',1,'']]],
  ['cell_5finfo_2',['cell_info',['../de/df1/structcell__info.html',1,'']]],
  ['chemical_5fdata_3',['chemical_data',['../da/d11/structchemical__data.html',1,'']]],
  ['cif_5fdata_4',['cif_data',['../d2/d95/structcif__data.html',1,'']]],
  ['classical_5ffield_5',['classical_field',['../d6/da3/structclassical__field.html',1,'']]],
  ['color_6',['color',['../d0/d91/structcolor.html',1,'']]],
  ['colormap_7',['colormap',['../d9/d58/structcolormap.html',1,'']]],
  ['colrgba_8',['ColRGBA',['../d1/d74/struct_col_r_g_b_a.html',1,'']]],
  ['coord_5fedition_9',['coord_edition',['../de/d4a/structcoord__edition.html',1,'']]],
  ['coord_5ffile_10',['coord_file',['../d0/d2f/structcoord__file.html',1,'']]],
  ['coord_5finfo_11',['coord_info',['../df/ddc/structcoord__info.html',1,'']]],
  ['cp2k_12',['cp2k',['../dd/d27/structcp2k.html',1,'']]],
  ['cpmd_13',['cpmd',['../da/d1f/structcpmd.html',1,'']]],
  ['crystal_5fdata_14',['crystal_data',['../d8/d1b/structcrystal__data.html',1,'']]],
  ['curve_15',['Curve',['../da/d6e/struct_curve.html',1,'']]],
  ['curve_5fdash_16',['curve_dash',['../d5/d03/structcurve__dash.html',1,'']]],
  ['curveextra_17',['CurveExtra',['../d8/dea/struct_curve_extra.html',1,'']]],
  ['curvestate_18',['CurveState',['../dd/d12/struct_curve_state.html',1,'']]]
];
